services:
  postgres:
    image: postgres:latest
    container_name: wallet-app-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - wallet-app-network

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    env_file:
      - config.env
    restart: unless-stopped
    networks:
      - wallet-app-network

networks:
  wallet-app-network:
    driver: bridge

volumes:
  postgres-data:
